version: '3.5'
services:
  nginx-guessit:
    image: nginx:1.15-alpine
    environment:
      - VIRTUAL_HOST=api.guessit.io
      - LETSENCRYPT_HOST=api.guessit.io
    volumes:
      - ./nginx-kong.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
  guessit:
    image: guessit/guessit-rest
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
