version: '3.5'
networks:
  nginx-proxy:
    external: true
services:
  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
  kong:
    image: kong:0.14.1-alpine
    command: kong start --run-migrations
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_SSL=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    expose:
      - 8000
      - 8001
    restart: unless-stopped
  nginx-kong:
    image: nginx:1.15-alpine
    environment:
      - VIRTUAL_HOST=${KONG_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${KONG_VIRTUAL_HOST}
    volumes:
      - ./nginx-kong.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
  nginx-kong-admin:
    image: nginx:1.15-alpine
    environment:
      - VIRTUAL_HOST=${KONG_ADMIN_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${KONG_ADMIN_VIRTUAL_HOST}
    volumes:
      - ./nginx-kong-admin.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
  kong-dashboard:
    image: pgbi/kong-dashboard:v3.5.0
    command: start --kong-url http://kong:8001
    environment:
      - VIRTUAL_HOST=${KONG_DASHBOARD_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${KONG_DASHBOARD_VIRTUAL_HOST}
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
volumes:
  database: ~
