version: '3.5'
networks:
  reverse-proxy:
    name: ${KONG_REVERSE_PROXY_NETWORK_NAME:-reverse-proxy}
    external: true
services:
  db:
    image: postgres:11.3
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    stdin_open: true
    tty: true
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: ${KONG_RESTART_POLICY:-unless-stopped}
  migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
    restart: on-failure
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-root}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    restart: ${KONG_RESTART_POLICY:-unless-stopped}
  nginx:
    image: nginx:1.15-alpine
    environment:
      - VIRTUAL_HOST=${KONG_VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${KONG_VIRTUAL_HOST}
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${KONG_VIRTUAL_HOST}'
      - traefik.port=80
    volumes:
      - ./nginx-kong.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - reverse-proxy
    restart: ${KONG_RESTART_POLICY:-unless-stopped}
  dashboard:
    image: pgbi/kong-dashboard:latest
    command: start --kong-url http://kong:8001 --basic-auth ${KONG_DASHBOARD_BASIC_AUTH}
    environment:
      - VIRTUAL_HOST=${KONG_DASHBOARD_VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${KONG_DASHBOARD_VIRTUAL_HOST}
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${KONG_DASHBOARD_VIRTUAL_HOST}'
      - traefik.port=8080
    networks:
      - default
      - reverse-proxy
    restart: ${KONG_RESTART_POLICY:-unless-stopped}
volumes:
  db-data: ~
